// Generated by CoffeeScript 1.6.2
(function() {
  var exec;

  exec = require('child_process').exec;

  exports.exec = function(cmd, callback) {
    var exe;

    exe = exec(cmd);
    exe.stdout.on('data', function(data) {
      return console.log(data.toString('utf8'));
    });
    exe.stderr.on('data', function(data) {
      return console.log(data.toString('utf8'));
    });
    return exe.on('close', function(code) {
      if (code === 0) {
        return typeof callback === "function" ? callback() : void 0;
      } else {
        return console.log('!! process exited with code ' + code);
      }
    });
  };

}).call(this);

/*
//@ sourceMappingURL=bbang.map
*/
